print("Olá, World!")
print("A IA irá te dominar...")
print("Tatake!")
print("Eu to tipo Uchiha Sasuke, ye")
print("Não espere coisas boas daqui")
print("Gerando decepção ao mundo desde 2003")
print("Não cederia meu lugar no avião")
print("Meu entreterimento basico sendo de Youtubers gays, amo <3")
print("Tô sem ideias, anyway")
print("Honkai Star Rail é melhor que Genshin Impact.")